appname: office-hours-ui
replicaCount: 1
image:
  tag: rossalli/office-hours-ui:v1

serviceAccount:
  create: true
  annotations: {}
  name: "office-hours-ui"
  account: "ui"

securityContext:
  enabled: false
  runAsUser: 1000

service:
  name: office-hours-ui
  type: ClusterIP
  ports:
   - name: http
     port: 9080
     
ingress:
  enabled: false
  
containerPort:
  enabled: true
  port: 9080

resources:
   limits:
    cpu: 256m
    memory: 256Mi
   requests:
    cpu: 128m
    memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

envVars:
  - name: LOG_DIR
    value: "/tmp/logs"

volume:
  enabled: true
  
livenessProbe:
  enabled: false
  failureThreshold: 3
  httpGet:
    path: /v1/healthcheck
    port: 9080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1  
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /v1/healthcheck
    port: 9080
    scheme: HTTP
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 1

istio:
  enabled: true
